"""Added RBAC and Feature Management

Revision ID: 255c104aee11
Revises: 59202cfc82bc
Create Date: 2025-01-28 17:14:38.393246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '255c104aee11'
down_revision = '59202cfc82bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    # ### end Alembic commands ###
